spring.application.name=transaction-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/transaction_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.show-sql=false

spring.flyway.locations=classpath:db/migrations
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
